services:
  zebrapose:
    image: zebrapose:latest
    build:
      context: .
      dockerfile: Dockerfile
    runtime: nvidia
    privileged: true
    stdin_open: true
    tty: true
    shm_size: '12g'
    devices:
      - /dev/dri:/dev/dri
    group_add:
      - video
    environment:
      - DISPLAY
      - TERM
      - QT_X11_NO_MITSHM=1
      - NVIDIA_DRIVER_CAPABILITIES=all
      - NVIDIA_VISIBLE_DEVICES=all  
    env_file:
      - .env
    volumes:
      - ./zebrapose:/zebrapose:rw
      - ${BOP_DATASET_PATH}:/zebrapose/bop_datasets:ro
      - ${CKPTS_PATH}:/zebrapose/zebrapose_ckpts:rw
      - ${RESULTS_PATH}:/zebrapose/zebrapose_results:rw
      - /tmp/.X11-unix:/tmp/.X11-unix